### ISSUE TITLE
Cartesian Coordinates vs Mercator Projection

### ISSUE THREAD

**Issue by oomti** [caduandrade/vector_map_flutter#13]
Currently this API only supports cartesian coordinates without Mercator Projection, it won't be ideal for a 1 on 1 mapping with other Map Services.

This is an example of overlaying a map with Mercator Projection and the example map from South America:

![image](https://github.com/caduandrade/vector_map_flutter/assets/23347037/8cd13f8f-fe71-4770-8f5f-229ff7fc562c)

**Comment by oomti** [comment]
The wireframe is the example from the vector_map_flutter API.
The background is a Google Map layer - I manually fit them together.

**Comment by caduandrade** [comment]
Hi @oomti.

Sorry for the delay in responding. Projection conversion is not within the scope of the API. The API will display any coordinate given the JSON. You will need to manually convert the coordinates before displaying.
