### ISSUE TITLE
Pan and Zoom

### ISSUE THREAD

**Issue by sWimmie** [caduandrade/vector_map_flutter#2]
Hi Carlos,

Thanks for your work on the vector_map_flutter package.
I was wondering if you got the chance to look into panning and zooming?
Or do you have any indication when you will get into it? It would be very helpful if this feature was added like you suggested in the Agenda for the next few days.

Thanks!
Wim

**Comment by caduandrade** [comment]
Hi @sWimmie ! Sorry for the delay in replying. I was camping on vacation.

I was working on more than one package at the same time (https://pub.dev/publishers/caduandrade.net/packages). The `Docking` package took priority.

The pan and zoom will take a little more work due to the optimizations. I think in November I'll be able to work on it.

But don't worry, I won't abandon the project ;-).

**Comment by sWimmie** [comment]
Hi @caduandrade! 
Always nice going camping! But thank you for the reply.
And of course I do understand that planning is hard with all the things we all have to do. 
It really would be a great feature and maybe I will dive into it myself if I can come around to it.

**Comment by caduandrade** [comment]
I created and maintained a vector map implementation in a Petrobras project. But it was in Java/Swing. In Flutter some things change. This is a really cool package to play with. :wink:

It would be easy if I just drew the original coordinates. As I'm focusing on a desktop project that can be used in heavy projects, my concern is to be able to display millions of coordinates. For this, there is the idea of multi-resolution to reduce the amount of coordinates. Simple example: don't draw multiple coordinates located on the same screen pixel.

Currently, the map is being fitted to screen size. Then you get a scale value that will be used to discard points.

There are others, but maybe these are two critical points in zoom/pan:

- In a very large zoom-in, the multi-resolution of geometry with millions of coordinates would discard no coordinates. It is necessary to understand how Flutter will handle this. The complete geometry won't fit on the screen but will the Skia engine try to draw the complete Path even with the clip?
- To prevent the same Path from being drawn all the time, there is a concept of "buffer" which is a screenshot. Drawing a raster image is faster than multiple paths that can overlap. When a Pan starts, you have to deal with the coordinates that were outside the image. I will try to ignore the buffer and draw a very low-resolution geometry while panning.

You're always welcome.

**Comment by caduandrade** [comment]
@sWimmie, almost done :wink: 

But now I think about what could be better. Unlimited or level-based zoom. Maybe both?

**Comment by sWimmie** [comment]
That is great! And I think both would be better. In a way that you can provide a level-based and the standard would be Unlimited?

**Comment by caduandrade** [comment]
I think the default may not be based on levels. Zoom increase or decrease the scale. Therefore, with or without levels, the scale cannot be unlimited because there are `Double` limits. I will also allow you to configure the maximum and minimum scale.

**Comment by caduandrade** [comment]
Updating all README and demo app. Improving DemoFlu became a prerequisite.

**Comment by caduandrade** [comment]
Finally finished. Contact me if you find any bugs or notice any functionality that is missing.

I noticed freezes on Mobile with heavy geometries (over 500k coordinates). I will investigate if there is any problem with the code and/or if I can improve it.
