### ISSUE TITLE
Paths are drawn mirrored and rotated

### ISSUE THREAD

**Issue by jstnw10** [caduandrade/vector_map_flutter#8]
Hey,

I am downloading some data from overpass api, converting them to GeoJSON and then parsing them. Here is what is expected for Bordeaux (this is an edited image):
![74253DF6-0681-49ED-97A8-7C04E70A5E04_1_201_a](https://user-images.githubusercontent.com/40317787/161403555-7c18957c-3c6f-4566-bc51-f950cc304ab8.jpeg)

Somehow what I get is the following:

![E607A8B7-6F05-4B05-9EA3-00F3FF8C60B6](https://user-images.githubusercontent.com/40317787/161403561-05616909-554d-4c5c-95bf-8f4b76fa737e.jpeg)

Hope you can help me to get it right, thanks for this package :)

**Comment by caduandrade** [comment]
Hi! The VectorMap only reads the received coordinates.

I believe it is some problem in converting OverpassAPI to GeoJSON. A common mistake is a vertical flip as the Y in the world coordinates is inverted with respect to the screen. In your case, a 90 degree rotation occurred. Maybe you inverted X and Y during the conversion.

Remember that Y means latitude and X means longitude in GIS. So, LatLong is YX ;-).

**Comment by jstnw10** [comment]
Sorry, you are completely right. I messed up Y and X 😆
